default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: sistema_facturacion
  pool: 5

development:
  <<: *default
